# site settings
title: Mughil Pari
subtitle: 
email: mughilan.muthupari@gmail.com
description: Master's in Data Science from Columbia University
baseurl: "" # the subpath of your site, e.g. /blog
url: https://mughilm.github.io # the base hostname & protocol for your site
author:
street_address: 14115 Bear Creek Drive
city: Boyds
state: MD
zip_code: 20841
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
